esphome:
  name: homemaster-opentherm
  friendly_name: HomeMaster OpenTherm Gateway
  project:
    name: homemaster.opentherm_gateway
    version: "1.0.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

wifi:
  ap:
    ssid: "HomeMaster OT Fallback"

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

dashboard_import:
  package_import_url: github://isystemsautomation/HOMEMASTER/OpenthermGateway/Firmware/opentherm.yaml@main
  import_full_config: true

http_request:

ota:
  - platform: esphome
  - platform: http_request

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://isystemsautomation.github.io/HOMEMASTER/OpenthermGateway/Firmware/manifest.json
    update_interval: 10s

opentherm:
  id: ot_bus
  in_pin: GPIO21
  out_pin: GPIO26

binary_sensor:
  - platform: gpio
    id: button_1
    name: "Button"
    pin:
      number: GPIO35
      mode:
        input: true

switch:
  - platform: gpio
    id: relay_1
    name: "Relay"
    pin: GPIO32

status_led:
  pin:
    number: GPIO33
    inverted: true