// HomeMaster estimator — generated by tools/build_web.mjs

const HM = globalThis.HM_ESTIMATOR = globalThis.HM_ESTIMATOR || {};

const HM_RULES_URL = (typeof globalThis !== "undefined" && (globalThis.HM_ESTIMATOR_RULES_URL || globalThis.HM_RULES_URL)) || "https://config.home-master.eu/estimator/rules.json";

HM.RULES_URL = HM_RULES_URL;


// ===== engine.js =====
/**
 * HomeMaster product configurator — pure estimation engine.
 * No fetch, DOM, Date.now, or Math.random.
 */

const EMPTY = Object.freeze({});

/**
 * @param {object} inputs
 * @param {object} rules
 * @param {object} [prices]
 * @returns {object}
 */
function estimate(inputs, rules, prices = EMPTY) {
  const assumptions = [];
  const normalized = normalize(inputs, rules, assumptions);
  const demand = buildDemand(normalized, rules);
  const allocated = allocate(demand, rules, assumptions);
  const topology = buildTopology(allocated, normalized, rules, assumptions);
  const power = computePower(topology.modules, rules, assumptions);
  const enclosure = computeEnclosure(topology.modules, rules);
  const priced = attachPrices(topology, power, enclosure, rules, prices, assumptions);
  return priced;
}

// ── Stage 1: normalize ──────────────────────────────────────────────

function normalize(inputs, rules, assumptions) {
  const out = {
    cabinets: inputs.cabinets ?? 1,
    mode: inputs.mode ?? "rooms",
    demand: {},
    shutters: 0,
    relay_needs_contactor: 0,
  };

  if (inputs.expert?.demand) {
    Object.assign(out.demand, inputs.expert.demand);
    out.mode = "expert";
    if (inputs.expert.shutters != null) out.shutters = inputs.expert.shutters;
    if (inputs.expert.relay_needs_contactor != null) {
      out.relay_needs_contactor = inputs.expert.relay_needs_contactor;
    }
    return out;
  }

  const mapping = rules.demand_mapping ?? EMPTY;
  const templates = rules.room_templates ?? EMPTY;

  if (inputs.rooms) {
    for (const room of inputs.rooms) {
      const tpl = templates[room.template ?? room.type] ?? room;
      for (const [field, channel] of Object.entries(mapping)) {
        if (channel === "shutters" || channel === "relay_needs_contactor") continue;
        const count = (tpl[field] ?? room[field] ?? 0) * (room.count ?? 1);
        if (count > 0) addDemand(out.demand, channel, count);
      }
    }
  }

  if (inputs.underfloor_circuits != null) {
    addDemand(out.demand, "out_24v_ch", inputs.underfloor_circuits);
  }
  if (inputs.shutters != null) {
    out.shutters = inputs.shutters;
  }
  if (inputs.relay_needs_contactor != null) {
    out.relay_needs_contactor = inputs.relay_needs_contactor;
  }

  const explicitFields = new Set([
    "cabinets",
    "rooms",
    "mode",
    "expert",
    "shutters",
    "relay_needs_contactor",
    "underfloor_circuits",
  ]);

  for (const [field, channel] of Object.entries(mapping)) {
    if (explicitFields.has(field)) continue;
    if (inputs[field] != null && channel !== "shutters" && channel !== "relay_needs_contactor") {
      addDemand(out.demand, channel, inputs[field]);
    }
  }

  return out;
}

function addDemand(bag, channel, qty) {
  bag[channel] = (bag[channel] ?? 0) + qty;
}

// ── Stage 2: demand ─────────────────────────────────────────────────

function buildDemand(normalized, _rules) {
  return {
    ...normalized.demand,
    shutters: normalized.shutters,
    relay_needs_contactor: normalized.relay_needs_contactor,
  };
}

// ── Stage 3: allocate ───────────────────────────────────────────────

function allocate(demand, rules, assumptions) {
  const modules = {};
  const accessories = [];
  const provenance = [];
  const remaining = { ...demand };
  delete remaining.shutters;
  delete remaining.relay_needs_contactor;

  const moduleSpecs = rules.modules ?? EMPTY;
  const slaves = Object.entries(moduleSpecs).filter(([, s]) => !s.master);

  // Shutters: each consumes one interlock_pair (2 relays) on a DIO.
  const shutterCount = demand.shutters ?? 0;
  let freeRelaysFromShutters = 0;
  if (shutterCount > 0) {
    addModule(modules, "DIO-430-R1", shutterCount, "shutter_interlock");
    freeRelaysFromShutters = shutterCount;
    provenance.push({
      kind: "shutters",
      qty: shutterCount,
      note: `Each shutter uses one interlock_pair on a DIO; ${freeRelaysFromShutters} free relay_out_3a credited toward relay demand.`,
    });
  }

  // Contactors accessory lines.
  const contactorCount = demand.relay_needs_contactor ?? 0;
  if (contactorCount > 0) {
    accessories.push({
      id: "contactor",
      qty: contactorCount,
      label: "External contactor (relay-driven load)",
      requirement: true,
    });
    provenance.push({ kind: "relay_needs_contactor", qty: contactorCount });
  }

  // Specialty channels in configured order.
  const order = rules.allocate_order ?? [];
  const specialtyMap = rules.specialty_modules ?? EMPTY;

  for (const channel of order) {
    const need = remaining[channel] ?? 0;
    if (need <= 0) continue;

    const modId = specialtyMap[channel];
    if (!modId) continue;

    const spec = moduleSpecs[modId];
    if (!spec) continue;

    let capacity;
    if (channel === "out_24v_ch") {
      const strCap = spec.provides?.out_24v_ch ?? 0;
      const policyCap = rules.policy?.str_actuators_per_module ?? 16;
      capacity = Math.min(strCap, policyCap);
    } else if (channel === "alarm_zone") {
      capacity = spec.provides?.alarm_zone ?? 0;
    } else if (channel === "energy_phase") {
      capacity = spec.provides?.energy_phase ?? 0;
    } else if (channel === "leak_or_pulse") {
      capacity = spec.provides?.leak_or_pulse ?? 0;
    } else if (channel === "pwm_led_ch") {
      capacity = spec.provides?.pwm_led_ch ?? 0;
    } else if (channel === "dimmer_ac_ch") {
      capacity = spec.provides?.dimmer_ac_ch ?? 0;
    } else if (channel === "opentherm") {
      capacity = spec.provides?.opentherm ?? 0;
    } else if (channel === "rtd_input") {
      capacity = spec.provides?.rtd_input ?? 0;
    } else if (channel === "analog_in") {
      capacity = spec.provides?.analog_in ?? 0;
    } else if (channel === "analog_out") {
      capacity = spec.provides?.analog_out ?? 0;
    } else if (channel === "presence_in") {
      capacity = spec.provides?.presence_in ?? 0;
    } else if (channel === "onewire") {
      capacity = spec.provides?.onewire ?? 0;
    } else {
      capacity = spec.provides?.[channel] ?? 0;
    }

    if (capacity <= 0) continue;

    const qty = Math.ceil(need / capacity);
    addModule(modules, modId, qty, `specialty:${channel}`);
    remaining[channel] = 0;
    provenance.push({ kind: "specialty", channel, module: modId, qty, need });
  }

  // Credit free relays from shutter DIOs toward relay_out_3a demand.
  let relayNeed = remaining.relay_out_3a ?? 0;
  if (freeRelaysFromShutters > 0 && relayNeed > 0) {
    const credit = Math.min(freeRelaysFromShutters, relayNeed);
    relayNeed -= credit;
    remaining.relay_out_3a = relayNeed;
    if (relayNeed === 0) delete remaining.relay_out_3a;
    provenance.push({
      kind: "shutter_relay_credit",
      credited: credit,
      remaining_relay_out_3a: relayNeed,
    });
  }

  // Universal relay_out_3a and di_dry — greedy by density, combined per module.
  const universalChannels = ["relay_out_3a", "di_dry"];
  const universalNeed = {};
  for (const ch of universalChannels) {
    const need = remaining[ch] ?? 0;
    if (need > 0) universalNeed[ch] = need;
  }

  if (Object.keys(universalNeed).length > 0) {
    const candidates = slaves
      .map(([id, s]) => {
        const caps = {};
        let score = 0;
        for (const ch of universalChannels) {
          caps[ch] = s.provides?.[ch] ?? 0;
          if (caps[ch] > 0 && universalNeed[ch]) score += caps[ch];
        }
        return { id, caps, score };
      })
      .filter((c) => c.score > 0)
      .sort((a, b) => b.score - a.score);

    if (candidates.length > 0) {
      const best = candidates[0];
      let qty = 0;
      for (const [ch, need] of Object.entries(universalNeed)) {
        const cap = best.caps[ch] ?? 0;
        if (cap > 0) qty = Math.max(qty, Math.ceil(need / cap));
      }
      addModule(modules, best.id, qty, "universal:relay_di");
      for (const ch of universalChannels) delete remaining[ch];
      provenance.push({ kind: "universal", channels: universalChannels, module: best.id, qty, need: universalNeed });
    }
  }

  // Reserve AFTER allocation: add whole modules (not by inflating demand).
  // Math.round so small BOMs (e.g. 2×DIO × 15% → 0) stay unchanged.
  const reservePct = rules.policy?.default_reserve_pct ?? 15;
  for (const [id, qty] of Object.entries({ ...modules })) {
    const extra = Math.round(qty * reservePct / 100);
    if (extra > 0) {
      addModule(modules, id, extra, "reserve");
      assumptions.push(
        `Reserve: +${extra}× ${id} (${reservePct}% of ${qty} allocated).`,
      );
    }
  }

  return { modules, accessories, provenance, remaining };
}

function addModule(bag, id, qty, source) {
  if (qty <= 0) return;
  bag[id] = (bag[id] ?? 0) + qty;
  if (!bag._sources) bag._sources = {};
  bag._sources[id] = bag._sources[id] ?? [];
  bag._sources[id].push(source);
}

// ── Stage 4: topology ───────────────────────────────────────────────

function buildTopology(allocated, normalized, rules, assumptions) {
  const moduleSpecs = rules.modules ?? EMPTY;
  const slaveIds = Object.keys(allocated.modules).filter((id) => {
    const spec = moduleSpecs[id];
    return spec && !spec.master;
  });

  const slaves = slaveIds.flatMap((id) => {
    const spec = moduleSpecs[id];
    const qty = allocated.modules[id];
    const lines = [];
    for (let i = 0; i < qty; i++) {
      lines.push({
        id,
        poll_weight: spec.poll_weight ?? 0,
        sku: spec.sku,
        tmpl_id: spec.product_template_id,
        product_id: spec.product_id,
        shop_url: spec.shop_url,
      });
    }
    return lines;
  });

  const segmentBudget = rules.bus?.segment_budget ?? 10;
  const hardMax = rules.bus?.hard_max_modules ?? 15;
  const minSegments = normalized.cabinets ?? 1;

  const segments = packSegments(slaves, segmentBudget, hardMax, minSegments);

  const controllers = rules.controllers ?? EMPTY;
  const threshold = controllers.small_slave_threshold ?? 4;
  const moduleMap = { ...allocated.modules };

  for (const seg of segments) {
    const slaveCount = seg.slaves.length;
    const ctrlId =
      slaveCount <= threshold ? controllers.small ?? "MicroPLC" : controllers.large ?? "MiniPLC";
    seg.controller = ctrlId;
    addModule(moduleMap, ctrlId, 1, "topology:controller");
  }

  const terminatorsPer = rules.terminators_per_segment ?? 2;
  for (const seg of segments) {
    seg.terminators = terminatorsPer;
    seg.poll_weight = seg.slaves.reduce((s, sl) => s + sl.poll_weight, 0);
  }

  const warnings = [];
  const warnAbove = rules.bus?.warn_above ?? 12;
  for (const seg of segments) {
    if (seg.slaves.length > warnAbove) {
      warnings.push(`Segment has ${seg.slaves.length} slaves (warn above ${warnAbove}).`);
    }
  }

  const esphome = buildEsphomeYaml(segments, rules);

  const modulesList = Object.entries(moduleMap)
    .filter(([id]) => id !== "_sources")
    .map(([id, qty]) => moduleLine(id, qty, moduleSpecs, allocated));

  return {
    modules: modulesList,
    accessories: allocated.accessories,
    provenance: allocated.provenance,
    topology: {
      segments,
      esphome_yaml: esphome,
      warnings,
    },
    assumptions,
  };
}

function packSegments(slaves, budget, hardMax, minSegments) {
  if (slaves.length === 0) {
    const segs = [];
    for (let i = 0; i < minSegments; i++) {
      segs.push({ slaves: [], poll_weight: 0 });
    }
    return segs;
  }

  // First-fit decreasing by poll_weight.
  const sorted = [...slaves].sort((a, b) => b.poll_weight - a.poll_weight);
  let segments = [{ slaves: [], poll_weight: 0 }];

  for (const slave of sorted) {
    let placed = false;
    for (const seg of segments) {
      const newWeight = seg.poll_weight + slave.poll_weight;
      const newCount = seg.slaves.length + 1;
      if (newWeight <= budget && newCount <= hardMax) {
        seg.slaves.push(slave);
        seg.poll_weight = newWeight;
        placed = true;
        break;
      }
    }
    if (!placed) {
      segments.push({ slaves: [slave], poll_weight: slave.poll_weight });
    }
  }

  while (segments.length < minSegments) {
    segments.push({ slaves: [], poll_weight: 0 });
  }

  return segments;
}

function buildEsphomeYaml(segments, rules) {
  const defs = rules.esphome_defaults ?? EMPTY;
  const lines = [
    "# RS-485 Modbus bus configuration",
    `# ${defs.comment ?? "Explicit timings required."}`,
    "",
  ];
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    lines.push(`modbus_controller:`);
    lines.push(`  - id: hm_segment_${i + 1}`);
    lines.push(`    update_interval: 1s`);
    lines.push(`    command_throttle: 0ms`);
    if (rules.bus?.requires_explicit_timings) {
      lines.push(`    turnaround_time: ${defs.turnaround_time ?? "100ms"}`);
      lines.push(`    send_wait_time: ${defs.send_wait_time ?? "250ms"}`);
    }
    lines.push(`    # slaves: ${seg.slaves.map((s) => s.id).join(", ") || "none"}`);
    lines.push("");
  }
  return lines.join("\n");
}

function moduleLine(id, qty, moduleSpecs, allocated) {
  const spec = moduleSpecs[id] ?? EMPTY;
  return {
    id,
    sku: spec.sku ?? `HM-${id}`,
    qty,
    tmpl_id: spec.product_template_id,
    product_id: spec.product_id,
    shop_url: spec.shop_url ?? "",
    provenance: allocated.modules._sources?.[id] ?? [],
  };
}

// ── Stage 5: power ──────────────────────────────────────────────────

function computePower(modulesList, rules, assumptions) {
  const moduleSpecs = rules.modules ?? EMPTY;
  const headroomPct = rules.policy?.psu_headroom_pct ?? 30;

  let logicW = 0;
  let fieldW = 0;
  const requirements = [];

  for (const line of modulesList) {
    const spec = moduleSpecs[line.id] ?? EMPTY;
    const pw = spec.power_w_max ?? 0;
    logicW += pw * line.qty;

    if (line.id === "RGB-621-R1" && line.qty > 0) {
      requirements.push({
        kind: "rgb_field_supply",
        text: `${line.qty}× RGB-621-R1: plan 5 A × 24 V field supply per module (120 W each) if strips are driven at full white.`,
      });
      fieldW += 120 * line.qty;
    }
    if (line.id === "STR-3221-R1" && line.qty > 0) {
      requirements.push({
        kind: "str_outputs",
        text: `${line.qty}× STR-3221-R1: 24 V actuator outputs — size external PSU for 3 A per active channel.`,
      });
      fieldW += 0.15 * 24 * 2 * line.qty;
    }
    if (line.id === "ALM-173-R1" && line.qty > 0) {
      requirements.push({
        kind: "alm_12v",
        text: `${line.qty}× ALM-173-R1: 12 V @ 150 mA per module for powered zones.`,
      });
      fieldW += 12 * 0.15 * line.qty;
    }
    if (line.id === "WLD-521-R1" && line.qty > 0) {
      requirements.push({
        kind: "wld_supply",
        text: `${line.qty}× WLD-521-R1: ~150 mA sensor supply budget per module.`,
      });
      fieldW += 3.6 * line.qty;
    }
    if (line.id === "AIO-422-R1" && line.qty > 0) {
      requirements.push({
        kind: "loop_power",
        text: `${line.qty}× AIO-422-R1: 4–20 mA loops — 20 mA × 24 V per active loop.`,
      });
    }
  }

  const moduleCount = modulesList.reduce((s, l) => s + l.qty, 0);
  const capacitanceUF = 330 * moduleCount;

  requirements.push({
    kind: "psu",
    text: `Logic PSU: (${logicW.toFixed(1)} W logic + ${fieldW.toFixed(1)} W field) × ${1 + headroomPct / 100} headroom ≈ ${((logicW + fieldW) * (1 + headroomPct / 100)).toFixed(1)} W total.`,
  });
  requirements.push({
    kind: "capacitance",
    text: `Bulk capacitance: ${capacitanceUF} µF recommended (330 µF × ${moduleCount} modules).`,
  });

  const totalW = (logicW + fieldW) * (1 + headroomPct / 100);

  return {
    logic_w: round1(logicW),
    field_w: round1(fieldW),
    total_w: round1(totalW),
    headroom_pct: headroomPct,
    capacitance_uF: capacitanceUF,
    requirements,
  };
}

function round1(n) {
  return Math.round(n * 10) / 10;
}

// ── Stage 6: enclosure ──────────────────────────────────────────────

function computeEnclosure(modulesList, rules) {
  const moduleSpecs = rules.modules ?? EMPTY;
  const missing = [];

  for (const line of modulesList) {
    const spec = moduleSpecs[line.id];
    if (!spec || spec.din_units == null) {
      missing.push(line.id);
    }
  }

  if (missing.length > 0) {
    return {
      status: "blocked",
      reason: "din_units_missing",
      modules: [...new Set(missing)],
    };
  }

  let dinTotal = 0;
  for (const line of modulesList) {
    const spec = moduleSpecs[line.id];
    dinTotal += (spec.din_units ?? 0) * line.qty;
  }

  const rows = Math.ceil(dinTotal / 24);

  return {
    status: "ok",
    din_total: dinTotal,
    rows,
  };
}

// ── Stage 7: price ──────────────────────────────────────────────────

function attachPrices(topologyResult, power, enclosure, rules, prices, assumptions) {
  const modules = topologyResult.modules.map((m) => ({
    ...m,
    price: prices[m.sku] ?? null,
  }));

  const accessories = topologyResult.accessories.map((a) => ({
    ...a,
    price: a.sku ? (prices[a.sku] ?? null) : null,
  }));

  const cart_lines = modules
    .filter((m) => m.sku?.startsWith("HM-"))
    .map((m) => ({
      tmpl_id: m.tmpl_id,
      product_id: m.product_id,
      qty: m.qty,
      sku: m.sku,
    }));

  const lines = [
    ...modules.map((m) => ({
      kind: "module",
      sku: m.sku,
      label: m.id,
      qty: m.qty,
      unit_price: m.price?.amount ?? null,
      currency: m.price?.currency ?? null,
      shop_url: m.shop_url,
    })),
    ...accessories.map((a) => ({
      kind: "accessory",
      sku: a.sku ?? "",
      label: a.label ?? a.id,
      qty: a.qty,
      unit_price: a.price?.amount ?? null,
      currency: a.price?.currency ?? null,
      requirement: a.requirement ?? false,
    })),
    ...power.requirements.map((r) => ({
      kind: "requirement",
      label: r.text,
      requirement: true,
    })),
  ];

  return {
    modules,
    accessories,
    cart_lines,
    topology: topologyResult.topology,
    power,
    enclosure,
    lines,
    assumptions: [...topologyResult.assumptions, ...assumptions],
    provenance: topologyResult.provenance,
  };
}

HM.estimate = estimate;

// ===== prices.js =====
/**
 * Runtime prices from Odoo shop Product ld+json.
 * Never baked into rules.json or the published artifact.
 */

const CACHE_PREFIX = "hm_price_";

/**
 * @param {unknown} node
 * @returns {object[]}
 */
function asArray(node) {
  if (node == null) return [];
  return Array.isArray(node) ? node : [node];
}

/**
 * Infer session currency from visible shop price chrome (not ld+json offer order).
 * Looks at span.oe_currency_value and nearby text (€, lei, EUR, RON, USD…).
 * @param {string} html
 * @returns {string|null}
 */
function detectCurrencyFromHtml(html) {
  if (!html) return null;
  if (typeof DOMParser !== "undefined") {
    const doc = new DOMParser().parseFromString(html, "text/html");
    const nodes = [
      ...doc.querySelectorAll("span.oe_currency_value"),
      ...doc.querySelectorAll("[data-website_sale_currency]"),
      ...doc.querySelectorAll(".product_price, .oe_price"),
    ];
    for (const node of nodes) {
      const chunk = `${node.textContent || ""} ${node.parentElement?.textContent || ""}`;
      const cur = currencyFromText(chunk);
      if (cur) return cur;
    }
  } else {
    // Node / no DOMParser: inspect text around the visible price widget only
    // (do not scan whole-document ld+json — that lists every currency).
    const re =
      /<span[^>]*class="[^"]*oe_currency_value[^"]*"[^>]*>[\s\S]*?<\/span>([\s\S]{0,80})/gi;
    let m;
    while ((m = re.exec(html)) !== null) {
      const cur = currencyFromText(m[0] + m[1]);
      if (cur) return cur;
    }
    const dataCur = html.match(/data-website_sale_currency=["']([A-Z]{3})["']/i);
    if (dataCur) return dataCur[1].toUpperCase();
  }
  return null;
}

/**
 * @param {string} text
 * @returns {string|null}
 */
function currencyFromText(text) {
  if (!text) return null;
  if (/€|\bEUR\b/i.test(text)) return "EUR";
  if (/\blei\b|\bRON\b/i.test(text)) return "RON";
  if (/\$|\bUSD\b/i.test(text)) return "USD";
  if (/£|\bGBP\b/i.test(text)) return "GBP";
  return null;
}

/**
 * Pick offer matching preferred currency; else first offer.
 * @param {object|object[]} offers
 * @param {string|null} preferredCurrency
 */
function pickOffer(offers, preferredCurrency) {
  const list = asArray(offers).flatMap((o) => {
    if (o && typeof o === "object" && Array.isArray(o.offers)) return o.offers;
    return [o];
  }).filter(Boolean);

  if (!list.length) return null;
  if (preferredCurrency) {
    const match = list.find(
      (o) => String(o.priceCurrency || "").toUpperCase() === preferredCurrency.toUpperCase(),
    );
    if (match) return { offer: match, currencyChosen: match.priceCurrency, ambiguous: false };
  }
  const first = list[0];
  return {
    offer: first,
    currencyChosen: first.priceCurrency || null,
    ambiguous: list.length > 1,
  };
}

/**
 * Parse Product ld+json from HTML via DOMParser (no regex over markup).
 * @param {string} html
 * @param {{ preferredCurrency?: string|null }} [opts]
 * @returns {{ sku: string, price: number, currency: string, available: boolean, currencyAmbiguous?: boolean } | null}
 */
function parseProductLdJson(html, opts = {}) {
  const preferred =
    opts.preferredCurrency ?? detectCurrencyFromHtml(html) ?? null;

  if (typeof DOMParser === "undefined") {
    return parseProductLdJsonFallback(html, { ...opts, preferredCurrency: preferred });
  }
  const doc = new DOMParser().parseFromString(html, "text/html");
  const scripts = doc.querySelectorAll('script[type="application/ld+json"]');
  for (const script of scripts) {
    let data;
    try {
      data = JSON.parse(script.textContent || "");
    } catch {
      continue;
    }
    for (const item of asArray(data)) {
      const types = asArray(item["@type"]).map(String);
      if (!types.includes("Product")) continue;
      const sku = item.sku || item.mpn;
      if (!sku) continue;
      const picked = pickOffer(item.offers, preferred);
      if (!picked) continue;
      const price = Number(picked.offer.price);
      if (!Number.isFinite(price)) continue;
      const avail = String(picked.offer.availability || "");
      return {
        sku: String(sku),
        price,
        currency: String(picked.currencyChosen || "EUR"),
        available: !avail || avail.includes("InStock") || avail.includes("LimitedAvailability"),
        currencyAmbiguous: picked.ambiguous,
      };
    }
  }
  return null;
}

/** Node-test helper without jsdom. */
function parseProductLdJsonFallback(html, opts) {
  const preferred =
    opts.preferredCurrency ?? detectCurrencyFromHtml(html) ?? null;
  const marker = 'type="application/ld+json"';
  let from = 0;
  while (from < html.length) {
    const i = html.indexOf(marker, from);
    if (i < 0) break;
    const start = html.indexOf(">", i) + 1;
    const end = html.indexOf("</script>", start);
    if (end < 0) break;
    from = end + 9;
    let data;
    try {
      data = JSON.parse(html.slice(start, end));
    } catch {
      continue;
    }
    for (const item of asArray(data)) {
      const types = asArray(item["@type"]).map(String);
      if (!types.includes("Product")) continue;
      const sku = item.sku || item.mpn;
      if (!sku) continue;
      const picked = pickOffer(item.offers, preferred);
      if (!picked) continue;
      const price = Number(picked.offer.price);
      if (!Number.isFinite(price)) continue;
      const avail = String(picked.offer.availability || "");
      return {
        sku: String(sku),
        price,
        currency: String(picked.currencyChosen || "EUR"),
        available: !avail || avail.includes("InStock"),
        currencyAmbiguous: picked.ambiguous,
      };
    }
  }
  return null;
}

function cacheGet(sku) {
  try {
    if (typeof sessionStorage === "undefined") return null;
    const raw = sessionStorage.getItem(CACHE_PREFIX + sku);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function cacheSet(sku, info) {
  try {
    if (typeof sessionStorage === "undefined") return;
    sessionStorage.setItem(CACHE_PREFIX + sku, JSON.stringify(info));
  } catch {
    /* ignore quota */
  }
}

/**
 * Detect shop session currency from the current page (visible price chrome).
 * @returns {string|null}
 */
function detectShopCurrency() {
  if (typeof document === "undefined") return null;
  return detectCurrencyFromHtml(document.documentElement?.outerHTML || "");
}

/**
 * @param {string} shopUrl
 * @param {{ preferredCurrency?: string|null, fetchImpl?: typeof fetch }} [opts]
 */
async function fetchPrice(shopUrl, opts = {}) {
  if (!shopUrl) return null;
  const fetchImpl = opts.fetchImpl || (typeof fetch !== "undefined" ? fetch : null);
  if (!fetchImpl) return { sku: "", price: NaN, currency: "", available: false, error: "no_fetch" };

  try {
    const res = await fetchImpl(shopUrl, { credentials: "same-origin" });
    if (!res.ok) {
      return { sku: "", price: NaN, currency: "", available: false, error: `http_${res.status}` };
    }
    const html = await res.text();
    // Prefer caller override, else currency from THIS product page's visible price,
    // else currency from the configurator host page session.
    const preferred =
      opts.preferredCurrency ??
      detectCurrencyFromHtml(html) ??
      detectShopCurrency();
    const parsed = parseProductLdJson(html, { preferredCurrency: preferred });
    if (!parsed) {
      return { sku: "", price: NaN, currency: "", available: false, error: "no_ldjson" };
    }
    cacheSet(parsed.sku, parsed);
    return parsed;
  } catch (err) {
    return {
      sku: "",
      price: NaN,
      currency: "",
      available: false,
      error: err instanceof Error ? err.message : "fetch_failed",
    };
  }
}

/**
 * @param {string[]} shopUrls
 * @param {{ preferredCurrency?: string|null, fetchImpl?: typeof fetch }} [opts]
 */
async function fetchPrices(shopUrls, opts = {}) {
  const map = new Map();
  const urls = [...new Set((shopUrls || []).filter(Boolean))];
  const sessionCurrency = opts.preferredCurrency ?? detectShopCurrency();
  for (const url of urls) {
    const info = await fetchPrice(url, {
      ...opts,
      preferredCurrency: opts.preferredCurrency ?? sessionCurrency,
    });
    if (info?.sku && Number.isFinite(info.price)) {
      map.set(info.sku, info);
      cacheSet(info.sku, info);
    } else if (info?.error) {
      map.set(url, info);
    }
  }
  return map;
}

/**
 * Convert Map / record from fetchPrices into the plain object `estimate()` expects.
 * Always keeps numeric prices; currencyAmbiguous is preserved as a flag only.
 * @param {Map<string, any>|Record<string, any>} prices
 * @returns {Record<string, { amount: number, currency: string, currencyAmbiguous?: boolean }>}
 */
function toEstimatePriceMap(prices) {
  const out = {};
  const entries = prices instanceof Map ? prices.entries() : Object.entries(prices || {});
  for (const [key, info] of entries) {
    if (!info || info.error || !Number.isFinite(info.price)) continue;
    const sku = info.sku || key;
    out[sku] = {
      amount: info.price,
      currency: info.currency || "EUR",
      currencyAmbiguous: !!info.currencyAmbiguous,
    };
  }
  return out;
}

HM.detectCurrencyFromHtml = detectCurrencyFromHtml;
HM.parseProductLdJson = parseProductLdJson;
HM.detectShopCurrency = detectShopCurrency;
HM.fetchPrice = fetchPrice;
HM.fetchPrices = fetchPrices;
HM.toEstimatePriceMap = toEstimatePriceMap;

// ===== cart.js =====
/**
 * Sequential Odoo Online cart add (one sale.order — no parallel writes).
 */

/**
 * @param {object} line
 * @param {{ fetchImpl?: typeof fetch, csrfToken?: string }} [opts]
 */
async function addCartLine(line, opts = {}) {
  const fetchImpl = opts.fetchImpl || fetch;
  const csrf =
    opts.csrfToken ||
    (typeof window !== "undefined" && window.odoo && window.odoo.csrf_token) ||
    "";
  const res = await fetchImpl("/shop/cart/add", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    credentials: "same-origin",
    body: JSON.stringify({
      jsonrpc: "2.0",
      method: "call",
      params: {
        product_template_id: line.tmpl_id,
        product_id: line.product_id,
        quantity: line.qty,
        csrf_token: csrf,
      },
    }),
  });
  if (!res.ok) {
    return { ok: false, line, error: `http_${res.status}` };
  }
  let body = null;
  try {
    body = await res.json();
  } catch {
    body = null;
  }
  if (body && body.error) {
    return { ok: false, line, error: body.error.message || "rpc_error", body };
  }
  return { ok: true, line, body };
}

/**
 * Add all HomeMaster cart_lines sequentially. Stops on first failure.
 * @param {Array<{tmpl_id:number, product_id:number, qty:number, sku:string}>} cartLines
 * @param {{ fetchImpl?: typeof fetch, csrfToken?: string }} [opts]
 * @returns {Promise<{ added: object[], failed: object|null }>}
 */
async function addAllToCart(cartLines, opts = {}) {
  const added = [];
  for (const line of cartLines || []) {
    const result = await addCartLine(line, opts);
    if (!result.ok) {
      return { added, failed: result };
    }
    added.push(result);
  }
  return { added, failed: null };
}

/**
 * @param {object} estimate
 * @returns {number}
 */
function cartLineCount(estimate) {
  return (estimate.cart_lines ?? []).reduce((s, l) => s + l.qty, 0);
}

/**
 * Sum HomeMaster lines that have a numeric price. Missing prices do not
 * null the whole subtotal; currencyAmbiguous never hides amounts.
 * @param {object} estimate
 * @param {Record<string, {amount: number, currency: string, currencyAmbiguous?: boolean}>} prices
 * @returns {{total: number, currency: string, pricedQty: number, missingSku: string[], currencyAmbiguous: boolean} | null}
 */
function cartTotal(estimate, prices) {
  let total = 0;
  let currency = null;
  let pricedQty = 0;
  let currencyAmbiguous = false;
  const missingSku = [];
  const lines =
    (estimate.cart_lines && estimate.cart_lines.length
      ? estimate.cart_lines
      : (estimate.modules || []).map((m) => ({ sku: m.sku, qty: m.qty }))) || [];
  for (const line of lines) {
    const p = prices[line.sku];
    if (!p || !Number.isFinite(p.amount)) {
      if (line.sku) missingSku.push(line.sku);
      continue;
    }
    total += p.amount * (line.qty || 1);
    currency = p.currency || currency || "EUR";
    pricedQty += line.qty || 1;
    if (p.currencyAmbiguous) currencyAmbiguous = true;
  }
  if (pricedQty === 0) return null;
  return {
    total: Math.round(total * 100) / 100,
    currency: currency || "EUR",
    pricedQty,
    missingSku,
    currencyAmbiguous,
  };
}

HM.addCartLine = addCartLine;
HM.addAllToCart = addAllToCart;
HM.cartLineCount = cartLineCount;
HM.cartTotal = cartTotal;

// ===== xlsx.js =====
/**
 * True .xlsx export via SheetJS (CDN). Formulas, not baked values.
 * SheetJS is loaded at runtime — not shipped in the public dist whitelist.
 */

const SHEETJS_CDN = "https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.mjs";

/** @type {Promise<any>|null} */
let xlsxPromise = null;

function loadXlsx() {
  if (!xlsxPromise) {
    xlsxPromise = import(SHEETJS_CDN);
  }
  return xlsxPromise;
}

/**
 * @param {object} estimate
 * @param {{ currency?: string }} [opts]
 * @returns {Promise<ArrayBuffer>}
 */
async function buildEstimateXlsx(estimate, opts = {}) {
  const XLSX = await loadXlsx();
  const currency = opts.currency || "EUR";
  const rows = [];

  rows.push(["HomeMaster estimate"]);
  rows.push([`Currency: ${currency}`]);
  rows.push(["Prices include VAT, same as the shopfront"]);
  rows.push([]);
  rows.push(["Section", "SKU / requirement", "Qty", "Unit price", "Line total"]);

  const sectionStarts = {};
  let r = 6; // 1-based excel row of first data line after header (row 5)

  function pushSection(title, lines, priceColFilled) {
    rows.push([title, "", "", "", ""]);
    r += 1;
    const start = r;
    for (const line of lines) {
      const qty = line.qty ?? 1;
      const price = line.unit_price;
      const priceCell = price != null && price !== "" ? Number(price) : "";
      rows.push([
        "",
        line.label || line.sku || line.requirement || "",
        qty,
        priceCell,
        // Formula D*E — SheetJS stores formula string
        { f: `D${r}*E${r}`.replace("D", "C").replace(/E(\d+)/, `D$1`) },
      ]);
      // Fix: columns are A section, B label, C qty, D unit, E total → E_r = C_r*D_r
      rows[rows.length - 1][4] = { f: `C${r}*D${r}` };
      r += 1;
    }
    const end = r - 1;
    sectionStarts[title] = { start, end };
    if (end >= start) {
      rows.push(["", `${title} subtotal`, "", "", { f: `SUM(E${start}:E${end})` }]);
    } else {
      rows.push(["", `${title} subtotal`, "", "", 0]);
    }
    r += 1;
    rows.push([]);
    r += 1;
  }

  const hm = (estimate.lines || []).filter((l) => l.kind === "homemaster" || l.sku);
  const acc = (estimate.lines || []).filter((l) => l.kind === "accessory" || l.kind === "companion");
  const work = (estimate.lines || []).filter((l) => l.kind === "labor" || l.kind === "work");
  const req = (estimate.lines || []).filter((l) => l.kind === "requirement" || l.requirement);

  // Fallback buckets from modules / accessories if lines thin
  const hmLines =
    hm.length > 0
      ? hm
      : (estimate.modules || []).map((m) => ({
          kind: "homemaster",
          sku: m.sku,
          label: m.id,
          qty: m.qty,
          unit_price: m.unit_price ?? "",
        }));
  const accLines =
    acc.length > 0
      ? acc
      : (estimate.accessories || []).map((a) => ({
          kind: "accessory",
          label: a.label || a.requirement || "Accessory",
          qty: a.qty ?? 1,
          unit_price: "",
        }));
  const workLines = work.length
    ? work
    : [{ kind: "work", label: "Installation / commissioning (user)", qty: 1, unit_price: "" }];
  const reqLines = req.length
    ? req
    : (estimate.power?.requirements || []).map((t) => ({
        kind: "requirement",
        label: t,
        qty: 1,
        unit_price: "",
      }));

  pushSection("HomeMaster", hmLines, true);
  const hmSubRow = r - 2;
  pushSection("Companion / materials", accLines, false);
  const accSubRow = r - 2;
  pushSection("Labor", workLines, false);
  const workSubRow = r - 2;
  pushSection("Requirements & assumptions", reqLines, false);

  rows.push(["VAT rate % (optional, user-filled)", "", "", "", ""]);
  const vatRateRow = r;
  r += 1;
  rows.push(["VAT amount (optional)", "", "", "", { f: `IF(D${vatRateRow}="", "", (E${hmSubRow}+E${accSubRow}+E${workSubRow})*D${vatRateRow}/100)` }]);
  r += 1;
  rows.push([]);
  r += 1;
  // Grand total: show text until all priced sections have numbers — formula awakens when filled
  rows.push([
    "Grand total",
    "",
    "",
    "",
    {
      f: `IF(OR(E${accSubRow}=0,E${workSubRow}=0),"fill in prices",E${hmSubRow}+E${accSubRow}+E${workSubRow})`,
    },
  ]);

  const ws = XLSX.utils.aoa_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Estimate");
  return XLSX.write(wb, { bookType: "xlsx", type: "array" });
}

/**
 * @param {object} estimate
 * @param {string} [filename]
 */
async function downloadXlsx(estimate, filename = "homemaster-estimate.xlsx") {
  const buf = await buildEstimateXlsx(estimate);
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** CSV fallback when SheetJS CDN is blocked */
function estimateToCsv(estimate) {
  const rows = [["Kind", "SKU", "Label", "Qty", "Unit price", "Currency"]];
  for (const line of estimate.lines ?? []) {
    rows.push([
      line.kind ?? "",
      line.sku ?? "",
      line.label ?? "",
      String(line.qty ?? ""),
      line.unit_price != null ? String(line.unit_price) : "",
      line.currency ?? "",
    ]);
  }
  return rows.map((r) => r.map(escapeCsv).join(",")).join("\n");
}

function escapeCsv(cell) {
  const s = String(cell);
  if (/[",\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function downloadCsv(estimate, filename = "homemaster-estimate.csv") {
  const csv = estimateToCsv(estimate);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

HM.buildEstimateXlsx = buildEstimateXlsx;
HM.downloadXlsx = downloadXlsx;
HM.estimateToCsv = estimateToCsv;
HM.downloadCsv = downloadCsv;

// ===== ui.js =====
/**
 * Four-step UI: Property → Rooms → Systems → Result.
 * Live summary; expert demand bypass; localStorage without prices.
 */




const STORAGE_KEY = "hm_configurator_v1";

const RULES_URL =
  (typeof globalThis !== "undefined" &&
    (globalThis.HM_ESTIMATOR_RULES_URL || globalThis.HM_RULES_URL)) ||
  "https://config.home-master.eu/estimator/rules.json";

/** @type {object|null} */
let rules = null;
/** @type {Record<string, {amount:number, currency:string, currencyAmbiguous?:boolean}>} */
let priceMap = {};
/** @type {object} */
let state = {
  step: 0,
  expert: false,
  object: { cabinets: 1, name: "" },
  rooms: [
    { template: "living", name: "Living room" },
    { template: "bedroom", name: "Bedroom" },
  ],
  engineering: {
    shutters: 0,
    underfloor_circuits: 0,
    dimmer_groups: 0,
    pwm_led_ch: 0,
    leak_zone: 0,
    flow_pulse: 0,
    rtd_input: 0,
    analog_in: 0,
    analog_in_4_20: 0,
    analog_out: 0,
    alarm_zone_powered: 0,
    alarm_zone_dry: 0,
    energy_phase: 0,
    onewire_sensor: 0,
    opentherm: false,
    relay_needs_contactor: 0,
  },
  expertDemand: {},
  rulesVersion: null,
};

const STEPS = ["Property", "Rooms", "Systems", "Result"];

async function loadRules(url = RULES_URL) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`rules ${res.status}`);
  rules = await res.json();
  return rules;
}

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;
    const saved = JSON.parse(raw);
    if (saved.rulesVersion && rules && saved.rulesVersion !== rules.version) return;
    Object.assign(state, saved, { rulesVersion: rules?.version });
  } catch {
    /* ignore */
  }
}

function saveState() {
  try {
    const rest = { ...state, rulesVersion: rules?.version };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(rest));
  } catch {
    /* ignore */
  }
}

function buildInputs() {
  if (state.expert) {
    return {
      cabinets: state.object.cabinets || 1,
      mode: "expert",
      expert: { demand: { ...state.expertDemand } },
    };
  }
  return {
    cabinets: state.object.cabinets || 1,
    rooms: state.rooms.map((r) => ({ template: r.template, name: r.name })),
    shutters: state.engineering.shutters || 0,
    underfloor_circuits: state.engineering.underfloor_circuits || 0,
    dimmer_groups: state.engineering.dimmer_groups || 0,
    pwm_led_ch: state.engineering.pwm_led_ch || 0,
    leak_zone: state.engineering.leak_zone || 0,
    flow_pulse: state.engineering.flow_pulse || 0,
    rtd_input: state.engineering.rtd_input || 0,
    analog_in: state.engineering.analog_in || 0,
    analog_in_4_20: state.engineering.analog_in_4_20 || 0,
    analog_out: state.engineering.analog_out || 0,
    alarm_zone_powered: state.engineering.alarm_zone_powered || 0,
    alarm_zone_dry: state.engineering.alarm_zone_dry || 0,
    energy_phase: state.engineering.energy_phase || 0,
    onewire_sensor: state.engineering.onewire_sensor || 0,
    opentherm: !!state.engineering.opentherm,
    relay_needs_contactor: state.engineering.relay_needs_contactor || 0,
  };
}

function runEstimate(inputs, prices = priceMap) {
  if (!rules) throw new Error("Rules not loaded");
  return estimate(inputs, rules, prices);
}

async function refreshPrices(result) {
  const urls = (result.modules || []).map((m) => m.shop_url).filter(Boolean);
  if (!urls.length) return;
  const map = await fetchPrices(urls, { preferredCurrency: detectShopCurrency() });
  priceMap = toEstimatePriceMap(map);
}

function formatPrice(p) {
  if (!p || typeof p.amount !== "number" || !Number.isFinite(p.amount)) {
    return '<span class="hm-muted">price unavailable</span>';
  }
  const amb = p.currencyAmbiguous
    ? ' <span class="hm-muted">(currency may not match shop session)</span>'
    : "";
  return `${p.amount} ${p.currency || ""}${amb}`;
}

function enclosureMessage(enclosure) {
  if (!enclosure || enclosure.status !== "blocked") {
    return `<p>DIN: ${enclosure?.din_total ?? "—"}</p>`;
  }
  if (enclosure.reason === "din_units_missing") {
    return `<p class="hm-warn">Panel layout: blocked — DIN width unknown for some modules</p>`;
  }
  return `<p class="hm-warn">Panel layout: blocked — ${enclosure.reason}</p>`;
}

function el(html) {
  const t = document.createElement("template");
  t.innerHTML = html.trim();
  return t.content.firstElementChild;
}

/**
 * @param {HTMLElement} root
 */
function mountConfigurator(root) {
  root.innerHTML = "";
  const shell = el(`
    <div class="hm-estimator">
      <header class="hm-estimator__header">
        <h1>HomeMaster</h1>
        <p class="hm-estimator__tagline">Panel configurator — calculated in your browser, prices from the shop</p>
        <label class="hm-expert"><input type="checkbox" id="hm-expert"> Expert mode (direct demand)</label>
      </header>
      <nav class="hm-steps" id="hm-steps"></nav>
      <div class="hm-layout">
        <main class="hm-main" id="hm-main"></main>
        <aside class="hm-summary" id="hm-summary"></aside>
      </div>
    </div>
  `);
  root.appendChild(shell);

  const stepsNav = shell.querySelector("#hm-steps");
  const main = shell.querySelector("#hm-main");
  const summary = shell.querySelector("#hm-summary");
  const expertCb = shell.querySelector("#hm-expert");

  expertCb.checked = !!state.expert;
  expertCb.addEventListener("change", () => {
    state.expert = expertCb.checked;
    saveState();
    render();
  });

  function renderSteps() {
    stepsNav.innerHTML = STEPS.map(
      (name, i) =>
        `<button type="button" class="hm-step ${i === state.step ? "is-active" : ""}" data-step="${i}">${i + 1}. ${name}</button>`,
    ).join("");
    stepsNav.querySelectorAll(".hm-step").forEach((btn) => {
      btn.addEventListener("click", () => {
        state.step = Number(btn.dataset.step);
        saveState();
        render();
      });
    });
  }

  function liveResult() {
    try {
      return runEstimate(buildInputs(), priceMap);
    } catch (err) {
      return { error: String(err) };
    }
  }

  function renderSummary(result) {
    if (result.error) {
      summary.innerHTML = `<p class="hm-warn">${result.error}</p>`;
      return;
    }
    const mods = (result.modules || [])
      .map((m) => {
        const p = priceMap[m.sku];
        return `<li><strong>${m.qty}×</strong> ${m.id}<br><span class="hm-muted">${formatPrice(p)}</span></li>`;
      })
      .join("");
    const tot = cartTotal(result, priceMap);
    let totalLine = "HomeMaster subtotal: —";
    if (tot && typeof tot.total === "number") {
      const amb = tot.currencyAmbiguous
        ? ' <span class="hm-muted">(currency may not match shop session)</span>'
        : "";
      totalLine = `HomeMaster subtotal: ${tot.total} ${tot.currency} (incl. VAT)${amb}`;
    }
    summary.innerHTML = `
      <h2>Summary</h2>
      <ul class="hm-modlist">${mods || "<li>—</li>"}</ul>
      <p>RS-485 segments: ${result.topology?.segments?.length ?? 0}</p>
      <p>24 V power: ${result.power?.total_w ?? "—"} W</p>
      ${enclosureMessage(result.enclosure)}
      <p class="hm-total">${totalLine}</p>
    `;
  }

  function renderObject() {
    main.innerHTML = `
      <h2>Property</h2>
      <label>Project name <input id="f-name" value="${state.object.name || ""}"></label>
      <label>Number of panels <input id="f-cab" type="number" min="1" value="${state.object.cabinets || 1}"></label>
      <div class="hm-actions"><button type="button" id="hm-next">Next</button></div>
    `;
    main.querySelector("#f-name").oninput = (e) => {
      state.object.name = e.target.value;
      saveState();
      bump();
    };
    main.querySelector("#f-cab").oninput = (e) => {
      state.object.cabinets = Number(e.target.value) || 1;
      saveState();
      bump();
    };
    main.querySelector("#hm-next").onclick = () => {
      state.step = state.expert ? 3 : 1;
      saveState();
      render();
    };
  }

  function renderRooms() {
    main.innerHTML = `
      <h2>Rooms</h2>
      <div id="room-list"></div>
      <button type="button" id="add-room">+ room</button>
      <div class="hm-actions">
        <button type="button" id="hm-back">Back</button>
        <button type="button" id="hm-next">Next</button>
      </div>
    `;
    const list = main.querySelector("#room-list");
    const templates = Object.keys(
      rules.room_templates || {
        living: 1,
        bedroom: 1,
        kitchen: 1,
        bath: 1,
      },
    );
    function paintRooms() {
      list.innerHTML = state.rooms
        .map(
          (r, i) => `
        <div class="hm-room-row" data-i="${i}">
          <input data-k="name" value="${r.name || ""}" placeholder="Name">
          <select data-k="template">${templates
            .map((t) => `<option value="${t}" ${t === r.template ? "selected" : ""}>${t}</option>`)
            .join("")}</select>
          <button type="button" data-rm="${i}">×</button>
        </div>`,
        )
        .join("");
      list.querySelectorAll(".hm-room-row").forEach((row) => {
        const i = Number(row.dataset.i);
        row.querySelectorAll("[data-k]").forEach((inp) => {
          inp.onchange = inp.oninput = () => {
            state.rooms[i][inp.dataset.k] = inp.value;
            saveState();
            bump();
          };
        });
        row.querySelector("[data-rm]").onclick = () => {
          state.rooms.splice(i, 1);
          saveState();
          paintRooms();
          bump();
        };
      });
    }
    paintRooms();
    main.querySelector("#add-room").onclick = () => {
      state.rooms.push({ template: "living", name: "" });
      saveState();
      paintRooms();
      bump();
    };
    main.querySelector("#hm-back").onclick = () => {
      state.step = 0;
      saveState();
      render();
    };
    main.querySelector("#hm-next").onclick = () => {
      state.step = 2;
      saveState();
      render();
    };
  }

  function renderEngineering() {
    const fields = [
      ["shutters", "Shutters / blinds (drives)"],
      ["underfloor_circuits", "Underfloor heating circuits"],
      ["dimmer_groups", "AC dimmer groups"],
      ["pwm_led_ch", "LED PWM channels"],
      ["leak_zone", "Leak zones"],
      ["flow_pulse", "Pulse meters"],
      ["rtd_input", "RTD inputs"],
      ["analog_in", "Analog inputs"],
      ["analog_in_4_20", "4–20 mA loops"],
      ["analog_out", "Analog outputs"],
      ["alarm_zone_powered", "Alarm zones (powered)"],
      ["alarm_zone_dry", "Alarm zones (dry contact)"],
      ["energy_phase", "Energy metering phases"],
      ["onewire_sensor", "1-Wire sensors"],
      ["relay_needs_contactor", "Relays needing contactor"],
    ];
    main.innerHTML = `
      <h2>Systems</h2>
      ${fields
        .map(
          ([k, label]) =>
            `<label>${label} <input data-eng="${k}" type="number" min="0" value="${state.engineering[k] || 0}"></label>`,
        )
        .join("")}
      <label class="hm-check"><input data-eng-bool="opentherm" type="checkbox" ${
        state.engineering.opentherm ? "checked" : ""
      }> OpenTherm boiler</label>
      <div class="hm-actions">
        <button type="button" id="hm-back">Back</button>
        <button type="button" id="hm-next">To result</button>
      </div>
    `;
    main.querySelectorAll("[data-eng]").forEach((inp) => {
      inp.oninput = () => {
        state.engineering[inp.dataset.eng] = Number(inp.value) || 0;
        saveState();
        bump();
      };
    });
    const ot = main.querySelector("[data-eng-bool]");
    ot.onchange = () => {
      state.engineering.opentherm = ot.checked;
      saveState();
      bump();
    };
    main.querySelector("#hm-back").onclick = () => {
      state.step = 1;
      saveState();
      render();
    };
    main.querySelector("#hm-next").onclick = () => {
      state.step = 3;
      saveState();
      render();
    };
  }

  function renderExpert() {
    main.innerHTML = `
      <h2>Expert demand (JSON)</h2>
      <textarea id="expert-json" rows="16">${JSON.stringify(state.expertDemand, null, 2)}</textarea>
      <div class="hm-actions">
        <button type="button" id="hm-apply">Apply</button>
        <button type="button" id="hm-next">To result</button>
      </div>
    `;
    main.querySelector("#hm-apply").onclick = () => {
      try {
        state.expertDemand = JSON.parse(main.querySelector("#expert-json").value || "{}");
        saveState();
        bump();
      } catch (e) {
        alert("JSON: " + e.message);
      }
    };
    main.querySelector("#hm-next").onclick = () => {
      state.step = 3;
      saveState();
      render();
    };
  }

  async function renderResult() {
    let result = liveResult();
    main.innerHTML = `<p>Loading prices from the shop…</p>`;
    await refreshPrices(result);
    result = liveResult();
    renderSummary(result);

    const mods = (result.modules || [])
      .map((m) => {
        const p = priceMap[m.sku];
        const priceCell =
          p && typeof p.amount === "number"
            ? `${p.amount} ${p.currency || ""}`
            : "—";
        return `<tr>
          <td>${m.qty}×</td>
          <td><a href="${m.shop_url || "#"}">${m.id}</a></td>
          <td>${m.sku}</td>
          <td>${priceCell}</td>
          <td><button type="button" class="hm-why" data-sku="${m.sku}">why</button></td>
        </tr>`;
      })
      .join("");

    main.innerHTML = `
      <h2>Result</h2>
      <table class="hm-table"><thead><tr><th>Qty</th><th>Module</th><th>SKU</th><th>Price incl. VAT</th><th></th></tr></thead>
      <tbody>${mods}</tbody></table>
      <details><summary>ESPHome YAML (bus timings)</summary>
        <pre>${(result.topology?.esphome_yaml || "").replace(/</g, "&lt;")}</pre>
      </details>
      <div class="hm-actions">
        <button type="button" id="hm-cart">Add to cart</button>
        <button type="button" id="hm-xlsx">Download .xlsx</button>
        <button type="button" id="hm-csv">CSV</button>
        <button type="button" id="hm-back">Back</button>
      </div>
      <div id="hm-cart-status"></div>
    `;

    main.querySelectorAll(".hm-why").forEach((btn) => {
      btn.onclick = () => {
        const m = result.modules.find((x) => x.sku === btn.dataset.sku);
        alert(JSON.stringify(m?.provenance || result.provenance || {}, null, 2));
      };
    });

    main.querySelector("#hm-xlsx").onclick = () =>
      downloadXlsx(result).catch(() => downloadCsv(result));
    main.querySelector("#hm-csv").onclick = () => downloadCsv(result);
    main.querySelector("#hm-back").onclick = () => {
      state.step = state.expert ? 0 : 2;
      saveState();
      render();
    };
    main.querySelector("#hm-cart").onclick = async () => {
      const status = main.querySelector("#hm-cart-status");
      status.textContent = "Adding…";
      const { added, failed } = await addAllToCart(result.cart_lines || []);
      if (failed) {
        status.innerHTML = `
          <p class="hm-warn">Added ${added.length} item(s); failed on ${failed.line?.sku}: ${failed.error}</p>
          <p><a href="/shop/cart">Open cart</a> · you can still download the estimate</p>`;
        return;
      }
      status.innerHTML = `<p>Done: ${added.length} item(s). <a href="/shop/cart">Go to cart</a></p>`;
    };
  }

  function bump() {
    renderSummary(liveResult());
  }

  function render() {
    renderSteps();
    if (state.expert && state.step > 0 && state.step < 3) {
      renderExpert();
      bump();
      return;
    }
    if (state.step === 0) renderObject();
    else if (state.step === 1) renderRooms();
    else if (state.step === 2) renderEngineering();
    else renderResult();
    if (state.step !== 3) bump();
  }

  render();
}

function findRoot() {
  if (typeof document === "undefined") return null;
  return (
    document.getElementById("hm-configurator") ||
    document.getElementById("hm-system-builder") ||
    document.querySelector("[data-hm-estimator]")
  );
}

async function init() {
  ensureStylesheet();
  await loadRules();
  loadState();
  const root = findRoot();
  if (root) mountConfigurator(root);
  else console.error("HM estimator: mount node not found (#hm-configurator / #hm-system-builder)");
}

function ensureStylesheet() {
  if (typeof document === "undefined") return;
  const href = "https://config.home-master.eu/estimator/app.css";
  if (
    [...document.querySelectorAll("link[rel='stylesheet']")].some((l) =>
      l.href.includes("/estimator/app.css"),
    )
  ) {
    return;
  }
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = href;
  document.head.appendChild(link);
}

function boot() {
  init().catch((err) => {
    const root = findRoot();
    if (root) {
      root.innerHTML = `<p class="hm-warn">Estimator failed: ${err?.message || err}</p>`;
    }
    console.error(err);
  });
}

if (typeof document !== "undefined") {
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot, { once: true });
  } else {
    boot();
  }
}

HM.loadRules = loadRules;
HM.runEstimate = runEstimate;
HM.mountConfigurator = mountConfigurator;
HM.init = init;


export { estimate, loadRules, runEstimate, mountConfigurator, init, fetchPrice, fetchPrices, addAllToCart, downloadXlsx };
